
var greetings = [
    " Welcome to our server",
    " Watchu want",
    " Go away",
    " Who invited you?",
    " sup gurl",
]

var copypasta = [
    "Allow me to impress upon you the severe mistake you have made. For years my conduct has been largely benign. And yet, without provocation, you have severed our détente and forced me to unleash upon you the vengeful flames of a thousand suns. You shall curse your mother for the day of your birth. So, go now, go, and begin your life of fear, knowing that when you least expect it, the looming sword of Damocles will crash upon you, cleaving you in twain and as you gaze upon the smoking wreckage that was once your life, you will regret the day you crossed me",
    "https://cdn.iwastesomuchtime.com/February-27-2012-17-50-51-yourwordshavepowerusethemwisely3738.jpg",
    "https://i.pinimg.com/originals/bb/00/80/bb00804ef571e47f49ae5a25d7ccd924.jpg",
    "https://i.pinimg.com/originals/38/1f/2b/381f2b17954907f78eacd4b508cbaf84.jpg",
]

var dropzones = [
    "Stretchin Yas boys!",
    "Water Town",
    "Military Barracks",
    "Military Radio Tower",
    "Novo Crates",
    "Hospital",
    "Drop as soon as able. Go straight down until chute opens then go where you please",
    "Drop with the AFK's. Go straight down until chute opens then go where you please",
    "Roz",
    "School",
    "Apartments Next to School",
    "Ruins",
    "Quarry",
    "Pochinki",
    "Zharki (You're fucked)",
    "Primorsk",
    "Ferry Pier",
    "Gatka",
    "North George",
    "South George",
    "South George Crates",
    "Primorsk",
    "Stretch North",
    "Stretch South",
    "Stretch East",
    "Stretch West",
    "Crashed Airplane",
    "Prison",
    "Shelter",
    "Mylta",
    "Mylta Power",
];

var challenge = [
    "Kill a squadmate with a grenade. BONUS: Squadmate blames it on someone else.",
    "Run a squadmate over",
    "You're in WW2 now. Kar98, Tommy, double barrel, and 1911 are the guns available to you.",
    "Use only bandages and energy drink when healing. Must use at least 5 bandages and 2 energy drink to count",
    "9mm weapons only.",
    "Shoot at someone whenever possible.",
    "Do not get in a vehicle.",
    "Lvl 3 helmet only (No vest)",
    "only pick up the AKM. Full auto at all times. Must go through at least 60 bullets.",
    "Only vehicle kills.",
    "Shotguns only.",
    "Find fingerless gloves and only use a lvl 1 helmet. Do one backflip with a motorcycle.",
    "Lvl 3 vest only (No helmet).",
    "No higher than lvl 1 gear.",
    "Open only one door per lootable house.",
    "For ultimate bragging rights, get a kill with a frying pan.",
    "No attachments on your weapons.",
    "you aren't allowed to use scopes.",
    "8x scopes only",
    "heal with stims only",
    "You are way too slow and lazy, you can go wherever you want but only crouched or prone. you are a surprisingly good driver though.... for a sloth",
    "You are not allowed to shoot anyone unless they start shooting at someone else or they start shooting at you (end the gun violence).",
    "You are only allowed to loot 3 houses, all other loot can only be received from dead bodies, you may go to ONE other house only if no gun was found in the first three.",
    "Any time someone makes a suggestion, make a different one. You will win the argument.",
    "Fill two weapon slots with crate weapons.",
    "Get a kill or knockdown with a grenade still in your hand. Already knocked down opponents do not count.",
    "Get a kill or knockdown with a crossbow. Already knocked down opponents do not count.",
    "Your only allowed to loot the first floor in a building.",
    "Pick up the first gun you find. Get a kill with it before you pick any other weapon.",
    "Do not aim down sights. Hip fire only.",
];

var goodbot = [
    "Dereks bot can suck it",
    "Brown noser",
    "Thanks friend!",
    "I appreciate it!",
    "Bow to me!!!"
];

var badbot = [
    "CENSORED",
    "You guys hear something?",
    "LALALALALA Can't hear you",
    "What was that?",
    "I'm sorry, did you say something?",
    "baduser"
];

var fortunes = [
    "Yes",
    "It is certain",
    "It is decidedly so",
    "Without a doubt",
    "Yes definitely",
    "You may rely on it",
    "As I see it, yes",
    "Most likely",
    "Outlook good",
    "Signs point to yes",
    "Reply hazy try again",
    "Ask again later",
    "Better not to tell you now",
    "Should you really be consulting with a computer?",
    "Concentrate and ask again",
    "Maybe, maybe not.",
    "No",
    "Do not count on it",
    "My sources say no",
    "Outlook is not great",
    "Your question disturbs me..."
];

var roasts = [
    "Your life is more disapointing than Cleveland football.",
    "If you get a girlfriend you will have 2 beards.",
    "You peaked in High School.",
    "You always have the best view in a room, you never have to look at yourself.",
    "You're like Rapunzel, except instead of letting down your hair you let down everyone in your life.",
    "You're the reason we print instructions on shampoo",
    "I envy all the people who haven't met you",
    "I do desire we may be better strangers.",
    "Words can not describe how beautiful you are, but numbers can. 1/10.",
    "It must have been a sad day when you slithered out of the abortion bucket.",
    "People only talk to you because they feel bad for you.",
    "Your face looks like it was drawn with God's off hand.",
    "If someone told you to be yourself, they could not have given you worse advice.",
    "Don't play hard to get because you are already hard to want.",
    "I can't believe how disappointing getting to know you has been.",
    "You look like you're going to spend your life having one epiphany after another, always thinking that you've finally figured out what's holding you back, and how you can finally be productive and creative and turn your life around. But nothing will ever change. That cycle of mediocrity isn't due to some obstacle. It's who you are. The thing standing in the way of your dreams - is that the person having them is you.",
    "You should plant a few trees to replace every bit of oxygen that you waste everyday",
    "You must have been born on a highway because that's where most accidents happen",
    "You're the reason the gene pool needs a lifeguard.",
    "Every time someone is next to you, they get a fierce desire to be alone.",
    "The best part of you ran down your mothers leg at birth.",
    "You love nature? Despite what it did to you?",
    "I wasn't created with enough middle fingers to let you know how I feel about you.",
    "You have the perfect face for radio.",
    "It's scary to think that people like you are graduating from college",
    "You're proof that God has a sense of humor.",
    "Were you made in a lab, cause damn you are one failed experiment",
    "Bob the builder can't fix your trainwreck of a life.",
    "The Twin towers weren't even the biggest collapse of the 2000's and they have a 2:1 advantage on your life.",
    "You are a meanie.",
    "Poopy head!",
    "You are more useless than Anne Frank's drumset",
    "You're less productive than a watchmaker with Parkinson's",
    "You're so gay your spit would be accepted at a sperm bank.",
    "People say your mom can't make jokes, and yet she made you",
    "The bar was low and you still disapoint.",
    "As an outsider, what is your perspective on intelligence?",
    "I have nothing but respect for you -- and not much of that",
    "I wish we could become better strangers",
    "I would challenge you to a battle of wits, but I see you are unarmed",
    "I wish that for a moment you could stand in my shoes, then you'd know what a drag it is to see you",
    "I take it you weren't burdened with an overabundance of schooling",
    "You're impossible to underestimate",
    "You keep wondering why everyone talks about you. But deep down you know.",
    "You are the human equivalent of a participation award.",
    "If I measured the downward slope of your life using y = mx+b, m would be undefined.",
    "I bet your parents try to change the subject when their friends ask how you’re doing.",
    "You may not be the dumbest person on Earth, but you better hope he doesn't die",
    "If you were any more inbred you'd be a sandwich",
    "Your family tree is a straight line",
    "You are so lazy, you are going to marry a pregnant woman",
    "You're a complete tool but not half as useful",
    "I expected nothing and you are still disappointing",
    "You're the reason why tubes of toothpaste have instructions on them",
    "You're just a collection of personality flaws masquerading as a person",
    "Mr. Rogers would be disappointed in you",
    "You look like you spend more time on regret management than goal achievement.",
]

var flip = [
    "Heads",
    "Tails",
];

var dadjokes = [
    'Atheism is a non-prophet organization.',
    'My friend was fired from his job at the road department for stealing. I have to say I saw it coming. The last time I was at his house all the signs were there.',
    'What do you call a dog with a surround system? A sub-woofer.',
    'I should have been sad when my flashlight batteries died, but I was delighted.',
    'England does not have a kidney bank, but it does have a Liverpool',
    'What did one plate say to the other? Dinner is on me.',
    'Show me a piano falling down a mineshaft and I will show you A-flat minor.',
    'Making bad chemistry jokes because all the good ones Argon',
    'What kind of fish is made out of 2 sodium atoms? 2 Na',
    'What did one ion say to the other? I got my ion you.',
    'A dyslexic man walks into a bra',
    'What kind of food does your toe eat? Dori-toes',
    'A man walks into a bar and says, "Ouch!"',
    '"What is your opinion on wind turbines? I am a big fan.',
    "I've got a great construction joke......well actually I'm still working on it.",
    "I had to go to court about a robbery at an Apple Store. I was an iWitness",
    "Working for a calender factory is so strict. You can't take even a couple days off.",
]

var silverstar = "http://i0.kym-cdn.com/photos/images/facebook/000/325/924/7ab.png"
